### ISSUE TITLE
Modal(Portal) not compatible with React Fiber (react@16)

### ISSUE THREAD

**Issue by cpunion** [Semantic-Org/Semantic-UI-React#1458]
### Version
semantic-ui-react@0.67.1
semantic-ui-css@2.2.9
react@16.0.0-alpha3
react-dom@16.0.0-alpha3

### Testcase
https://github.com/cpunion/TestSemanticUIWithFiber

See:
https://github.com/cpunion/TestSemanticUIWithFiber/blob/master/src/index.js

Errors:
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Portal.renderPortal (Portal.js:348)
    at Portal.componentDidUpdate (Portal.js:291)
    at commitLifeCycles (ReactFiberCommitWork.js:431)
    at commitAllLifeCycles (ReactFiberScheduler.js:349)
    at HTMLUnknownElement.boundFunc (ReactErrorUtils.js:81)
    at ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:95)
    at commitAllWork (ReactFiberScheduler.js:468)
    at completeUnitOfWork (ReactFiberScheduler.js:610)
    at performUnitOfWork (ReactFiberScheduler.js:637)
    at workLoop (ReactFiberScheduler.js:760)
renderPortal @ Portal.js:348
componentDidUpdate @ Portal.js:291
commitLifeCycles @ ReactFiberCommitWork.js:431
commitAllLifeCycles @ ReactFiberScheduler.js:349
boundFunc @ ReactErrorUtils.js:81
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:95
commitAllWork @ ReactFiberScheduler.js:468
completeUnitOfWork @ ReactFiberScheduler.js:610
performUnitOfWork @ ReactFiberScheduler.js:637
workLoop @ ReactFiberScheduler.js:760
boundFunc @ ReactErrorUtils.js:81
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:95
performWork @ ReactFiberScheduler.js:802
batchedUpdates @ ReactFiberScheduler.js:1245
performFiberBatchedUpdates @ ReactGenericBatching.js:32
stackBatchedUpdates @ ReactGenericBatching.js:23
batchedUpdates @ ReactGenericBatching.js:37
batchedUpdatesWithControlledComponents @ ReactGenericBatching.js:50
dispatchEvent @ ReactEventListener.js:174
Portal.js:259 Uncaught TypeError: Cannot read property 'removeEventListener' of null
    at Portal._this.unmountPortal (Portal.js:259)
    at Portal.componentWillUnmount (Portal.js:301)
    at callComponentWillUnmountWithTimerInDev (ReactFiberCommitWork.js:59)
    at HTMLUnknownElement.boundFunc (ReactErrorUtils.js:81)
    at ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:95)
    at safelyCallComponentWillUnmount (ReactFiberCommitWork.js:67)
    at commitUnmount (ReactFiberCommitWork.js:338)
    at unmountHostComponents (ReactFiberCommitWork.js:278)
    at commitDeletion (ReactFiberCommitWork.js:309)
    at commitAllHostEffects (ReactFiberScheduler.js:326)
Portal._this.unmountPortal @ Portal.js:259
componentWillUnmount @ Portal.js:301
callComponentWillUnmountWithTimerInDev @ ReactFiberCommitWork.js:59
boundFunc @ ReactErrorUtils.js:81
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:95
safelyCallComponentWillUnmount @ ReactFiberCommitWork.js:67
commitUnmount @ ReactFiberCommitWork.js:338
unmountHostComponents @ ReactFiberCommitWork.js:278
commitDeletion @ ReactFiberCommitWork.js:309
commitAllHostEffects @ ReactFiberScheduler.js:326
boundFunc @ ReactErrorUtils.js:81
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:95
commitAllWork @ ReactFiberScheduler.js:428
completeUnitOfWork @ ReactFiberScheduler.js:610
performFailedUnitOfWork @ ReactFiberScheduler.js:667
clearErrors @ ReactFiberScheduler.js:698
workLoop @ ReactFiberScheduler.js:765
boundFunc @ ReactErrorUtils.js:81
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:95
performWork @ ReactFiberScheduler.js:802
batchedUpdates @ ReactFiberScheduler.js:1245
performFiberBatchedUpdates @ ReactGenericBatching.js:32
stackBatchedUpdates @ ReactGenericBatching.js:23
batchedUpdates @ ReactGenericBatching.js:37
batchedUpdatesWithControlledComponents @ ReactGenericBatching.js:50
dispatchEvent @ ReactEventListener.js:174
ReactFiberErrorLogger.js:53 React caught an error thrown by Portal. You should fix this error in your code. Consider adding an error boundary to your tree to customize error handling behavior.

TypeError: Cannot read property 'addEventListener' of null

The error is located at: 
    in Portal (created by Modal)
    in Modal (at index.js:9)
    in App (at index.js:20)

The error was thrown at: 
    at Portal.renderPortal (http://localhost:4444/static/js/bundle.js:52626:23),
    at Portal.componentDidUpdate (http://localhost:4444/static/js/bundle.js:52569:13),
    at commitLifeCycles (http://localhost:4444/static/js/bundle.js:32987:25),
    at commitAllLifeCycles (http://localhost:4444/static/js/bundle.js:28776:10),
    at HTMLUnknownElement.boundFunc (http://localhost:4444/static/js/bundle.js:16512:15),
    at ReactErrorUtils.invokeGuardedCallback (http://localhost:4444/static/js/bundle.js:16526:17),
    at commitAllWork (http://localhost:4444/static/js/bundle.js:28895:20),
    at completeUnitOfWork (http://localhost:4444/static/js/bundle.js:29037:12),
    at performUnitOfWork (http://localhost:4444/static/js/bundle.js:29064:15),
    at workLoop (http://localhost:4444/static/js/bundle.js:29187:27)
logCapturedError @ ReactFiberErrorLogger.js:53
commitErrorHandling @ ReactFiberScheduler.js:1063
commitAllLifeCycles @ ReactFiberScheduler.js:363
boundFunc @ ReactErrorUtils.js:81
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:95
commitAllWork @ ReactFiberScheduler.js:468
completeUnitOfWork @ ReactFiberScheduler.js:610
performFailedUnitOfWork @ ReactFiberScheduler.js:667
clearErrors @ ReactFiberScheduler.js:698
workLoop @ ReactFiberScheduler.js:765
boundFunc @ ReactErrorUtils.js:81
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:95
performWork @ ReactFiberScheduler.js:802
batchedUpdates @ ReactFiberScheduler.js:1245
performFiberBatchedUpdates @ ReactGenericBatching.js:32
stackBatchedUpdates @ ReactGenericBatching.js:23
batchedUpdates @ ReactGenericBatching.js:37
batchedUpdatesWithControlledComponents @ ReactGenericBatching.js:50
dispatchEvent @ ReactEventListener.js:174
Portal.js:348 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Portal.renderPortal (Portal.js:348)
    at Portal.componentDidUpdate (Portal.js:291)
    at commitLifeCycles (ReactFiberCommitWork.js:431)
    at commitAllLifeCycles (ReactFiberScheduler.js:349)
    at HTMLUnknownElement.boundFunc (ReactErrorUtils.js:81)
    at ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:95)
    at commitAllWork (ReactFiberScheduler.js:468)
    at completeUnitOfWork (ReactFiberScheduler.js:610)
    at performUnitOfWork (ReactFiberScheduler.js:637)
    at workLoop (ReactFiberScheduler.js:760)
```

**Comment by cpunion** [comment]
I tested all components, only the Portal not work, it affects Popup, Modal, and Confirm. I will try to find the reason.

Another is Search:

```
react-dom.min.js:13 Uncaught TypeError: Cannot read property 'length' of undefined
    at Search._this.tryOpen (http://localhost:8080/app.6a0b31ffffbd008a43de.js:39972:24)
    at Search._this.handleInputClick (http://localhost:8080/app.6a0b31ffffbd008a43de.js:39862:14)
    at Object.invokeGuardedCallback (http://cdnjs.cloudflare.com/ajax/libs/react/16.0.0-alpha.4/react-dom.min.js:13:26452)
    at Object.invokeGuardedCallbackAndCatchFirstError (http://cdnjs.cloudflare.com/ajax/libs/react/16.0.0-alpha.4/react-dom.min.js:13:26592)
    at i (http://cdnjs.cloudflare.com/ajax/libs/react/16.0.0-alpha.4/react-dom.min.js:12:17214)
    at Object.u [as executeDispatchesInOrder] (http://cdnjs.cloudflare.com/ajax/libs/react/16.0.0-alpha.4/react-dom.min.js:12:17454)
    at d (http://cdnjs.cloudflare.com/ajax/libs/react/16.0.0-alpha.4/react-dom.min.js:12:14727)
    at v (http://cdnjs.cloudflare.com/ajax/libs/react/16.0.0-alpha.4/react-dom.min.js:12:14853)
    at Array.forEach (native)
    at r (http://cdnjs.cloudflare.com/ajax/libs/react/16.0.0-alpha.4/react-dom.min.js:15:24725)
```
