### ISSUE TITLE
import {ALL_ICONS_IN_ALL_CONTEXTS} from 'semantic-ui-react/src/lib/SUI';

### ISSUE THREAD

**Issue by tyliec** [Semantic-Org/Semantic-UI-React#1986]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
import {ALL_ICONS_IN_ALL_CONTEXTS} from 'semantic-ui-react/src/lib/SUI';

### Expected Result
imports ALL_ICONS_... correctly

### Actual Result
```
Uncaught SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/me/Desktop/.../node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/me/Desktop/.../file.jsx:13:12)
    at Object.<anonymous> (/Users/tylerchong/Desktop/.../file.jsx:167:3)
```
### Version
0.70.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

**Comment by layershifter** [comment]
`src` contains our source, your bundler cannot include it because it's not `cjs`/`es` module. If you want import from `src`, configure [your loader](https://github.com/babel/babel-loader#usage) correctly if you're using webpack.

---

If you just need icons, use transpiled code:

```js
import {ALL_ICONS_IN_ALL_CONTEXTS} from 'semantic-ui-react/dist/commonjs/lib/SUI'
```

However, I don't recomend to rely on them. It's our internal API and I want to perform some optimizations of this file in future.
