### ISSUE TITLE
I update to v0.71.5 have a window is not defined

### ISSUE THREAD

**Issue by thinnakrit** [Semantic-Org/Semantic-UI-React#2005]
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/Thinnakrit/Documents/Massdrop Project/git/web-next/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/V
isibility.js:260:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxxxxxxxxx/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/i
ndex.js:8:19)
    at Module._compile (module.js:569:30)
ReferenceError: window is not defined
    at Object.<anonymous> (/xxxxxxxxxx/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/V
isibility.js:260:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxxxxxxxxx/node_modules/semantic-ui-react/dist/commonjs/behaviors/Visibility/i
ndex.js:8:19)
    at Module._compile (module.js:569:30)
```

 i downgrade to use v0.71.4, can run !

**Comment by layershifter** [comment]
Duplicate #1987.
