### ISSUE TITLE
Remove console.group

### ISSUE THREAD

**Issue by mousemke** [Semantic-Org/Semantic-UI-React#272]
in their words:

```
This feature is non-standard and is not on a standards track. Do not use it on production.
```

https://developer.mozilla.org/en-US/docs/Web/API/Console/group

our other option here is literally to fork stardust and start ripping things out (which we have already started)

**Comment by levithomason** [comment]
`console.group` is only used in development.  The code for grouping is removed in production via webpack's dead code elimination.  You can see this by the lack of debug logging on the doc site.  The doc site is built with `NODE_ENV=production`.

That said, the debug module is a recent addition and I'm also not completely satisfied with it.  The goals are:
- Allow turning on/off debugging for specific components
- Show method call order
- Allow developers to insert extra debug info inside method calls
- Do no debug in production

Better suggestions or a PR improving the current debug module is welcome.

**Comment by mousemke** [comment]
To clarify, in my issue mocha won't process the file in node due to console.group. I'll look for a solution and PR if I find something

**Comment by levithomason** [comment]
What's the error you get with mocha?

**Comment by mousemke** [comment]
```
> _mocha ./test/test.js --compilers js:babel-register --R nyan -r ignore-styles -r mock-local-storage -r ./test/test-setup;

/Library/WebServer/Documents/backoffice/node_modules/stardust/dist/utils/debug.js:41
    inst.group = console.group.bind(console, msg);
                              ^

TypeError: Cannot read property 'bind' of undefined
    at makeDebugger (/Library/WebServer/Documents/backoffice/node_modules/stardust/dist/utils/debug.js:41:31)
    at Object.<anonymous> (/Library/WebServer/Documents/backoffice/node_modules/stardust/dist/utils/debug.js:56:19)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Library/WebServer/Documents/backoffice/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:458:32)
```

etc etc for about 60 lines  because things

we played around with changing the call in the debug to make the `.group` into a noop and it worked to some degree, but that feels like more of a hack than a fix

**Comment by levithomason** [comment]
Makes sense.  Either it should be shimmed or pulled out.  I'll start a PR for the latter.

**Comment by levithomason** [comment]
@mousemke I just released `v0.15.0`.  That should solve this for you.  Thanks for report.

**Comment by avinlakhera** [comment]
I have also getting this issue 

PS D:\megameeting\mm4-react\mm4_peer> npm run react-test

> megameeting@1.0.0 react-test D:\megameeting\mm4-react\mm4_peer
> mocha --require ./react/src/jsDom/setup.js ./node_modules/babel-core/register --compilers js:./node_modules/babel-core
/register ./react/src/test/*.js

Semantic-UI-React could not enable debug.
TypeError: Cannot read property 'debug' of undefined
    at Object.<anonymous> (D:\megameeting\mm4-react\mm4_peer\node_modules\semantic-ui-react\dist\commonjs\lib\debug.js:2
2:33)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-reg
ister\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\megameeting\mm4-react\mm4_peer\node_modules\semantic-ui-react\dist\commonjs\lib\index.js:7
7:14)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-reg
ister\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\megameeting\mm4-react\mm4_peer\node_modules\semantic-ui-react\dist\commonjs\addons\Respons
ive\Responsive.js:43:12)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-reg
ister\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\megameeting\mm4-react\mm4_peer\node_modules\semantic-ui-react\dist\commonjs\addons\Respons
ive\index.js:8:19)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-reg
ister\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\megameeting\mm4-react\mm4_peer\node_modules\semantic-ui-react\dist\commonjs\index.js:7:19)

    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-reg
ister\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:/megameeting/mm4-react/mm4_peer/react/src/component/MenuItems.jsx:2:1)
    at Module._compile (module.js:635:30)
    at loader (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-re
gister\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:/megameeting/mm4-react/mm4_peer/react/src/component/App.jsx:2:1)
    at Module._compile (module.js:635:30)
    at loader (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-re
gister\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:/megameeting/mm4-react/mm4_peer/react/src/test/firsttest.js:4:1)
    at Module._compile (module.js:635:30)
    at loader (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\megameeting\mm4-react\mm4_peer\node_modules\babel-reg
ister\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at D:\megameeting\mm4-react\mm4_peer\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\megameeting\mm4-react\mm4_peer\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (D:\megameeting\mm4-react\mm4_peer\node_modules\mocha\lib\mocha.js:514:10)
    at Object.<anonymous> (D:\megameeting\mm4-react\mm4_peer\node_modules\mocha\bin\_mocha:480:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/reac
t-polyfills
Inside First

**Comment by layershifter** [comment]
https://stackoverflow.com/a/43935800/6488546
