### ISSUE TITLE
Error when running yarn build

### ISSUE THREAD

**Issue by hudovisk** [Semantic-Org/Semantic-UI-React#3141]
## Bug Report
Error when running `yarn build`

### Steps
node -v: `v8.11.3`

Forked repo,
Git clone,
run `yarn`
run `yarn build`

### Expected Result
Build Successful

### Actual Result
```
15:45:50 ➜  Semantic-UI-React git:(master) yarn build
yarn run v1.9.2
$ cross-env NODE_ENV=production gulp build
[15:46:09] Requiring external module @babel/register
[15:46:14] Using gulpfile ~/Documents/Projetos/Semantic-UI-React/gulpfile.babel.js
[15:46:14] Starting 'build'...
[15:46:14] Starting 'dll'...
[15:46:14] Starting 'clean:dll'...
[15:46:14] Finished 'clean:dll' after 81 ms
[15:46:14] Starting 'build:dll'...
[15:46:20] Time: 5581ms
        Asset     Size  Chunks                    Chunk Names
dll.vendor.js  9.16 MB       0  [emitted]  [big]  vendor

WARNING in ./node_modules/prettier/standalone.js
7397:15-64 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compiler.js:502:17)
    at /Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
 @ ./node_modules/prettier/standalone.js
 @ dll vendor
[15:46:20] 'build:dll' errored after 5.74 s
[15:46:20] Error in plugin 'webpack'
Message:
    ./node_modules/prettier/standalone.js
7397:15-64 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compiler.js:502:17)
    at /Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/Users/hudoassenco/Documents/Projetos/Semantic-UI-React/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
 @ ./node_modules/prettier/standalone.js
 @ dll vendor
Details:
    domain: [object Object]
    domainThrown: true
[15:46:20] 'dll' errored after 5.82 s
[15:46:20] 'build' errored after 5.82 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Version
latest

### Testcase
Simple fork: https://github.com/hudovisk/Semantic-UI-React

**Comment by layershifter** [comment]
Thanks for the amazing report 👍 

It comes from `prettier` update: https://github.com/prettier/prettier/issues/4959. Fix is coming.

**Comment by hudovisk** [comment]
@layershifter Thanks for the quick fix! but I am not able to run `yarn build` yet. I believe it is something to do with some babel upgrade.

```
➜  Semantic-UI-React git:(master) yarn build
yarn run v1.9.4
$ cross-env NODE_ENV=production gulp build
[15:03:55] Requiring external module @babel/register
[15:04:06] Using gulpfile ~/Projects/Semantic-UI-React/gulpfile.babel.js
[15:04:06] Starting 'build'...
[15:04:06] Starting 'dll'...
[15:04:06] Starting 'clean:dll'...
[15:04:06] Finished 'clean:dll' after 4.57 ms
[15:04:06] Starting 'build:dll'...
[15:04:14] Time: 8038ms
        Asset     Size  Chunks                    Chunk Names
dll.vendor.js  8.43 MB       0  [emitted]  [big]  vendor
[15:04:14] Finished 'build:dll' after 8.47 s
[15:04:14] Finished 'dll' after 8.48 s
[15:04:14] Starting 'build:dist'...
[15:04:14] Starting 'build:docs'...
[15:04:14] Starting 'build:dist:commonjs'...
[15:04:14] Starting 'build:dist:es'...
[15:04:14] Starting 'build:dist:umd'...
[15:04:14] Starting 'build:dist:commonjs:js'...
[15:04:14] Starting 'build:dist:commonjs:tsd'...
[15:04:15] Starting 'build:docs:toc'...
[15:04:15] Starting 'clean:docs'...
[15:04:15] Starting 'clean:docs:component-info'...
[15:04:15] Starting 'clean:docs:component-menu'...
[15:04:15] Starting 'clean:docs:dist'...
[15:04:15] Starting 'clean:docs:example-menus'...
[15:04:15] Starting 'clean:docs:example-sources'...
[15:04:15] Finished 'clean:docs:component-info' after 16 ms
[15:04:15] Finished 'clean:docs:component-menu' after 17 ms
[15:04:15] Finished 'clean:docs:dist' after 17 ms
[15:04:15] Finished 'clean:docs:example-menus' after 17 ms
[15:04:15] Finished 'clean:docs:example-sources' after 17 ms
[15:04:15] Finished 'clean:docs' after 20 ms
[15:04:15] Starting 'build:docs:json'...
[15:04:15] Starting 'build:docs:docgen'...
[15:04:15] Starting 'build:docs:component-menu'...
[15:04:15] Starting 'build:docs:example-menu'...
[15:04:15] Starting 'build:docs:example-sources'...
[15:04:20] 'build:dist:es' errored after 6 s
[15:04:20] Error: Command failed: cross-env NODE_ENV=build-es babel /Users/hudoassenco/Projects/Semantic-UI-React/src -d /Users/hudoassenco/Projects/Semantic-UI-React/dist/es
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
    at validatePlugins (/Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/parser/lib/index.js:10407:13)
    at getParser (/Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/parser/lib/index.js:10464:5)
    at parse (/Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/parser/lib/index.js:10448:12)
    at parser (/Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /Users/hudoassenco/Projects/Semantic-UI-React/node_modules/@babel/core/lib/transform-file.js:58:36
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
[15:04:20] 'build:dist' errored after 6 s
[15:04:20] 'build' errored after 14 s
[15:04:21] The following tasks did not complete: build:docs, build:dist:commonjs, build:dist:umd, <parallel>, build:dist:commonjs:js, build:dist:commonjs:tsd, build:docs:toc, <series>, build:docs:json, build:docs:docgen, build:docs:component-menu, build:docs:example-menu, build:docs:example-sources
[15:04:21] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by layershifter** [comment]
@hudovisk thank you for feedback :+1: Pushed also #3145, after it build was successfull:

```
[21:35:23] Finished 'build:dist:umd' after 58 s
[21:35:23] Finished 'build:dist' after 58 s
=> Fetching Site Data...
=> [✓] Site Data Downloaded: 4.753ms
=> Fetching Route Data...
=> [=======================================================================================================] 950/950 100% 3455/s 0.0s
=> [✓] Route Data Downloaded: 284.081ms
=> Exporting Route Data...
=> [✓] Route Data Exported: 212.660ms
=> Exporting Shared Route Data...
=> Exporting HTML...
=> [=] 1/1 100% Infinity/s 0.0s
=> [========================================================================================================--] 931/950 98% 69/s 0.3s=> [✓] HTML Exported: 15948.413ms
=> [=========================================================================================================] 950/950 100% 70/s 0.0s
=> [✓] Shared Route Data Exported: 47463.156ms
[21:37:24] Finished 'build:docs:static:build' after 2.32 min
[21:37:24] Finished 'build:docs' after 2.97 min
[21:37:24] Finished 'build' after 3.1 min
Done in 193.66s.
```
