### ISSUE TITLE
Build: A fresh build fails locally

### ISSUE THREAD

**Issue by AlanFoster** [Semantic-Org/Semantic-UI-React#3225]
### Steps

- Git clone semantic-ui-react
- Run `yarn`
- Run `yarn build`

### Expected Result
Yarn build completes successfully

### Actual Result

Yarn build did not complete succesfully, and outputs a stack trace

```
[00:51:54] Finished 'build:dist:umd' after 13 s
[00:51:54] Finished 'build:dist' after 13 s

=> Fetching Site Data...
=> [✓] Site Data Downloaded: 3.383ms
=> Fetching Route Data...
=> [=====================================================================================================================] 971/971 100% 4954/s 0.0s
=> [✓] Route Data Downloaded: 199.249ms
=> Exporting Route Data...
=> [✓] Route Data Exported: 63.297ms
=> Exporting Shared Route Data...
=> Exporting HTML...

{ Invariant Violation: Failed exporting HTML for URL 404 (docs/src/pages/PageNotFound): Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at invariant (/Users/dev/Documents/code/Semantic-UI-React/node_modules/fbjs/lib/invariant.js:42:15)
    at z (/Users/dev/Documents/code/Semantic-UI-React/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:11:166)
    at a.render (/Users/dev/Documents/code/Semantic-UI-React/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:16)
    at a.read (/Users/dev/Documents/code/Semantic-UI-React/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:288)
    at renderToString (/Users/dev/Documents/code/Semantic-UI-React/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:6)
    at renderToStringAndExtract (/Users/dev/Documents/code/Semantic-UI-React/node_modules/react-static/lib/static/index.js:519:68)
    at Object.renderToHtml (/Users/dev/Documents/code/Semantic-UI-React/node_modules/react-static/lib/static/getConfig.js:278:14)
    at _callee8$ (/Users/dev/Documents/code/Semantic-UI-React/node_modules/react-static/lib/static/index.js:556:39)
    at tryCatch (/Users/dev/Documents/code/Semantic-UI-React/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/dev/Documents/code/Semantic-UI-React/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22) name: 'Invariant Violation', framesToPop: 1 }
[00:52:59] The following tasks did not complete: build, <parallel>, build:docs, build:docs:static:build
[00:52:59] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  Semantic-UI-React git:(master)
```

### Version
master (845c3479d98b6094a816384132926cfb48bde4df)

**Comment by layershifter** [comment]
Will be fixed in #3218.
