### ISSUE TITLE
How do I build from git?

### ISSUE THREAD

**Issue by NullVoxPopuli** [Semantic-Org/Semantic-UI-React#3414]
I'm using node 10.14.2

Because I need a yet-to-be-released bugfix (on 0.84, upgraded from 0.80 (0.84 broke all my radio/checkboxes, need 0.85, but hasn't been released yet), I tried to build semantic-ui-react as part of my start command.

In my package.json I have: 
```
  "scripts": {
    "remove-semantic-types": "( cd node_modules/semantic-ui-react && yarn && yarn build:dist) && rm -f node_modules/semantic-ui-react/index.d.ts",
    "webpack-dev": "./node_modules/.bin/webpack-dev-server",
    "tslint": "./node_modules/.bin/tslint -c ./tslint.json --project ./tsconfig.json",
    "start:dev": "yarn remove-semantic-types && REVISION=$(git rev-parse HEAD) BUILD_DATE=$(date) yarn webpack-dev",
  },


    "semantic-ui-react": "github:Semantic-Org/Semantic-UI-React#d56ce7191fe802b1ee4dd82c9acb7520723fafe5",
```

So, there is a bit going on in there, but the key thing is the command `remove-semantic-types`, which was initially created because the type definitions in 0.84 are very broken, so I just removed them so I could keep trying to get work done.

But this: is the main code of concern here for running semantic-ui-react from git:
```
cd node_modules/semantic-ui-react && yarn && yarn build:dist
```
when I run that, I get the following error:

```
$ cd node_modules/semantic-ui-react && yarn && yarn build:dist
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.61s.
yarn run v1.12.3
$ gulp --series build:dist
/home/lprestonsegoiii/Development/Work/Clients/SIL/Scriptoria/appbuilder-portal/source/SIL.AppBuilder.Portal.Frontend/node_modules/semantic-ui-react/gulp/tasks/dist.js:1
(function (exports, require, module, __filename, __dirname) { import { dest, task, series, src, parallel } from 'gulp'
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (project-path/node_modules/semantic-ui-react/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (project-path/node_modules/semantic-ui-react/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So... how do I build semantic-ui-react?

The only documentation I found related to build was releasing -- but that's really only relevant for those who maintain the npm package.

I did see that it runs `yarn prerelease`... so... I ran that and got this error:

```
$ yarn prerelease
yarn run v1.12.3
$ yarn lint && yarn tsd:lint && yarn tsd:test && yarn test && cross-env NODE_ENV=production yarn build
$ cross-env NODE_ENV=production eslint .

Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-@typescript-eslint". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-@typescript-eslint is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-@typescript-eslint@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So.. I guess that needs to be installed globally... (it should really be a dev dep of semantic-ui-react).
but anyway, now I'm doing this: 
```
cd node_modules/semantic-ui-react && npm install -g @typescript-eslint/eslint-plugin && yarn && yarn prelease 
```

but that gave me the same error... so... then maybe I'll just change the dev deps :-\
```
cd node_modules/semantic-ui-react && \
  yarn && \
  yarn add --dev @typescript-eslint/eslint-plugin @typescript-eslint/parser && \
  yarn prerelease 
```

that didn't work either... same error.

`which eslint` returns nothing, so I don't have eslint installed globally.

I searched the repo for `@typescript`, but couldn't find anything. 
where is this error coming from?

Also, running `$ NODE_ENV=production yarn build` gives the same unexpected token error as above with `build:dist`

**Comment by NullVoxPopuli** [comment]
Update, it seems if I do 
```
git clone git@github.com:Semantic-Org/Semantic-UI-React.git && \
  cd Semantic-UI-React && \
  yarn && yarn prerelease
```

it works... with node 8 .... so now... in my package.json script, I'm doing this:

```bash
 ( \
    cd node_modules && \
      rm -rf semantic-ui-react && \
      git clone git@github.com:Semantic-Org/Semantic-UI-React.git semantic-ui-react && \
      cd semantic-ui-react && \
      nvm use 8 && \ 
      yarn && \
      NODE_ENV=production yarn build \
)
```

but that still doesn't work.

trying the cloned repo outside my project on node 10 seems to work. 
so... this has some sort of issue with being inside a node_modules folder inside another repo? O.O

**Comment by NullVoxPopuli** [comment]
Maybe if I cd to the system tmp directory to build?

This is complicated enough where I've pulled this out into an external script

package.json:
```
    "build-deps": "scripts/build-dependencies.sh $PWD",
```

```bash
#!/bin/bash

set -ex

if [[ ! -d node_modules/semantic-ui-react/dist ]]; then
  echo "semantic-ui-react has not been built!"
  echo "PWD: $1"
  
  cd /tmp
  rm -rf semantic-ui-react
  git clone git@github.com:Semantic-Org/Semantic-UI-React.git semantic-ui-react
  cd /tmp/semantic-ui-react
  yarn install
  NODE_ENV=production yarn build:dist
  mv /tmp/semantic-ui-react $1/node_modules/

  echo "building semantic-ui-react has finished"
else
  echo "semantic-ui-react has already been built"
fi

# types are broken
rm -rf "$1/node_modules/semantic-ui-react/index.d.ts"
```


this worked
