### ISSUE TITLE
Dimmer: Cannot read property 'setProperty' of undefined

### ISSUE THREAD

**Issue by laplacesdemon** [Semantic-Org/Semantic-UI-React#3518]
## Bug Report

After I upgraded to 0.86, some of my tests started failing with following error message:

### Expected Result
No fail

### Actual Result

```
TypeError: Cannot read property 'setProperty' of undefined

       96 | describe('<MyComponent />', () => {
       97 |   it('should match snapshot', () => {
    >  98 |     const component = renderer.create(<MyComponent  />);
          |                                ^
       99 |     const tree = component.toJSON();
      100 |     expect(tree).toMatchSnapshot();
      101 |   });

      at DimmerInner.toggleStyles (../node_modules/semantic-ui-react/dist/commonjs/modules/Dimmer/DimmerInner.js:95:28)
      at DimmerInner.componentDidMount (../node_modules/semantic-ui-react/dist/commonjs/modules/Dimmer/DimmerInner.js:79:12)
      at commitLifeCycles (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9411:22)
      at commitAllLifeCycles (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10808:7)
      at HTMLUnknownElement.callCallback (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2377:14)
      at invokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2427:16)
      at invokeGuardedCallback (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2480:31)
      at commitRoot (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11020:7)
      at ../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12471:5
      at Object.unstable_runWithPriority (../node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12470:13)
      at performWorkOnRoot (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12399:9)
      at performWork (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12307:7)
      at performSyncWork (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12281:3)
      at requestWork (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12150:5)
      at scheduleWork (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11965:5)
      at scheduleRootUpdate (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12564:3)
      at updateContainerAtExpirationTime (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12592:10)
      at updateContainer (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12603:10)
      at Object.create (../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13036:5)
      at Object.create 

```

### Version
0.86.0

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/54703516-9cf88180-4b41-11e9-8741-9ee8ccd70246.png)

`containerRef.current` doesn't contain the `style` property when is rendered with `react-test-renderer`. PR is coming.
