### ISSUE TITLE
Support server side rendering

### ISSUE THREAD

**Issue by Johnsel** [Semantic-Org/Semantic-UI-React#364]
Hello everyone,

I'm getting some window reference errors while trying to render from the server. Should put a mock window library in place or is there some other recommended approach?

Thanks!

John

**Comment by levithomason** [comment]
I bet it is due to `utils/jquery.js`.  Can you confirm?  If so, I think a simple check for the window here will solve it.

**Comment by Johnsel** [comment]
Oops, that's a shitty report. Yes, indeed utils/jquery.js threw localStorage and some jQuery errors but that latter might be due to a missing package (not sure if that renders on the server properly out of the box)

**Comment by levithomason** [comment]
Could you provide a repro repo or paste the errors here to be sure we hit them all?

**Comment by Johnsel** [comment]
Yup, one second please.

**Comment by Johnsel** [comment]
Stardust debug disabled. The browser could not write to localStorage. ReferenceError: localStorage is not defined
    at Object.<anonymous> (/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/stardust/dist/utils/debug.js:16:5)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/stardust/dist/utils/jquery.js:7:14)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/stardust/dist/utils/jquery.js:19
if (window.jQuery) jQuery = window.jQuery;else if ((0, _get3.default)(window, '$.prototype.jquery')) jQuery = window.$;
    ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/stardust/dist/utils/jquery.js:19:5)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/stardust/dist/index.js:8:1)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/johnsimons/Dropbox/WebstormProjects/node.js/itg/itg-webstack-boilerplate/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by levithomason** [comment]
See #365 for the fix, will merge and release soon.

**Comment by Johnsel** [comment]
Thank you, testing it now, stand by...

**Comment by levithomason** [comment]
Released in `v0.27.5`, let me know if there are further issues.  Cheers.

**Comment by Johnsel** [comment]
Confirmed, thanks for the support & fix!

**Comment by levithomason** [comment]
💥 awesome, I want to do some server side rendering here at TA soon as well.  LMK if there are any further issues or features needed.
