### ISSUE TITLE
not working with clean create-react-app out of box, loader(s) missing?

### ISSUE THREAD

**Issue by ylli2000** [Semantic-Org/Semantic-UI-React#4313]
### Steps

> A clear and concise description of steps to reproduce the problem.

A clean install of `npx create-react-app my-app` followed by `yarn add semantic-ui-react semantic-ui-css` 

```
package.json

    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^2.0.4",
    "web-vitals": "^2.1.2"
```

Then insert `import 'semantic-ui-css/semantic.min.css'; ` into line 1 of `index.js`

Then run `yarn start` the following errors are showing up, and could not compile successfully...

It seems to me like image loader, and other loader(s) may be missing. Am I supposed to add it manually?
If so, could you please give me instructions and show me what loader(s) are needed?

### Expected Result

> The result that you expected.

```
Compiled successfully!

You can now view my-app in the browser.

Local:            http://localhost:3000        
On Your Network:  http://192.168.1.101:3000     
```

### Actual Result

> The actual result that happened 💣
_(note that the string64 chunks are cutout, you can see the original in the screenshot picture below)_

```
Failed to compile.

Module build failed: UnhandledSchemeError: Reading from "data:application/x-font-ttf**...(cutout)**" is not handled by plugins (Unhandled scheme).        
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "data:" URIs.
assets by path static/ 9.45 KiB
  asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.88 KiB [emitted] 1 related asset
  asset static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg 2.57 KiB [emitted] (auxiliary name: main)
asset index.html 1.62 KiB [emitted]
asset asset-manifest.json 429 bytes [emitted]
Entrypoint main (2.57 KiB) = 1 auxiliary asset
cached modules 2.69 MiB (javascript) 1.66 MiB (asset) 31.3 KiB (runtime) [cached] 146 modules
runtime modules 54 bytes 1 module
data:application/x-font-ttf**...(cutout)** 42 bytes (javascript) 1 bytes (asset) [built] [1 error]

ERROR in data:application/x-font-ttf**...(cutout)**
Module build failed: UnhandledSchemeError: Reading from "data:application/x-font-ttf**...(cutout)**" is not handled by plugins (Unhandled scheme).        
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "data:" URIs.
    at E:\my-app\node_modules\webpack\lib\NormalModule.js:825:25
    at Hook.eval [as callAsync] (eval at create (E:\my-app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\my-app\node_modules\tapable\lib\Hook.js:18:14)
    at Object.processResource (E:\my-app\node_modules\webpack\lib\NormalModule.js:822:8)
    at processResource (E:\my-app\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (E:\my-app\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (E:\my-app\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (E:\my-app\node_modules\webpack\lib\NormalModule.js:812:3)
    at NormalModule.build (E:\my-app\node_modules\webpack\lib\NormalModule.js:956:15)
    at E:\my-app\node_modules\webpack\lib\Compilation.js:1367:12
 @ ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/semantic-ui-css/semantic.min.css 22:37-5903
 @ ./node_modules/semantic-ui-css/semantic.min.css 8:6-230 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-200 83:0-200 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/index.js 4:0-42

ERROR in [entry] [initial]
Cannot read property 'get' of undefined
during rendering of asset asset/inline|data:application**...(cutout)**
TypeError: Cannot read property 'get' of undefined
during rendering of asset asset/inline|data:application**...(cutout)**
    at E:\my-app\node_modules\webpack\lib\asset\AssetModulesPlugin.js:183:30
    at Hook.eval [as call] (eval at create (E:\my-app\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:12:16)
    at Hook.CALL_DELEGATE [as _call] (E:\my-app\node_modules\tapable\lib\Hook.js:14:14)
    at Compilation.getRenderManifest (E:\my-app\node_modules\webpack\lib\Compilation.js:4439:36)
    at E:\my-app\node_modules\webpack\lib\Compilation.js:4459:22
    at symbolIterator (E:\my-app\node_modules\neo-async\async.js:3482:9)
    at timesSync (E:\my-app\node_modules\neo-async\async.js:2297:7)
    at Object.eachLimit (E:\my-app\node_modules\neo-async\async.js:3463:5)
    at Compilation.createChunkAssets (E:\my-app\node_modules\webpack\lib\Compilation.js:4452:12)
    at E:\my-app\node_modules\webpack\lib\Compilation.js:3095:14

webpack 5.65.0 compiled with 2 errors in 2159 ms
```

### Version

```
$ yarn add semantic-ui-react semantic-ui-css
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > tailwindcss@3.0.7" has unmet peer dependency "autoprefixer@^10.0.2".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.0" has unmet peer dependency "typescript@>= 2.7".
warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 15 new dependencies.
info Direct dependencies
├─ semantic-ui-css@2.4.1
└─ semantic-ui-react@2.0.4
```
```
$ nvm list

  * 17.0.1 (Currently using 64-bit executable)
    16.3.0
    14.16.1
    13.2.0
    8.16.2
```

### Screenshot (partial)

![err](https://user-images.githubusercontent.com/2382820/147416839-69c60079-9814-4637-8260-56bdde33a61c.png)

**Comment by ylli2000** [comment]
Patch solution found:

The main reason for this is an extra ";" at line 19990 of semantic.css If removed, everything goes fine.

@font-face {
  font-family: 'Step';
  src: url(data:application/x-font-ttf;charset=utf-8;;base64,AAEAAAA... // this line
}

https://stackoverflow.com/questions/70367443/create-react-app-with-typescript-failing-to-compile-after-importing-semantic-ui
